### ISSUE TITLE
File Size exactly the same in output 

### ISSUE THREAD

**Issue by nicolasalexandre21** [PacificBiosciences/extracthifi#2]
Hello,

I ran the following:

source activate pbccs
ccs m64044_210320_005327.subreads.bam 1_ccs.bam &
ccs m64044_210424_010328.subreads.bam 2_ccs.bam &
wait

My output files have the exact same file output size? What does this mean?

-rw-r--r-- 1 nalexandre ucb 23866075838 Jun  6 13:25 1_ccs.bam
-rw-r--r-- 1 nalexandre ucb 31342720526 Jun  7 05:07 2_ccs.bam
-rw-r--r-- 1 nalexandre ucb 23866075838 Sep  1 12:43 HiFi1.bam
-rw-r--r-- 1 nalexandre ucb 31342720526 Sep  1 12:48 HiFi2.bam

**Comment by armintoepfer** [comment]
Your ccs call only generates HiFi data. Have a look at https://ccs.how/faq/reads-bam

**Comment by nicolasalexandre21** [comment]
Thank you!
